version: "3"
services:
  node01:
    image: launcher.gcr.io/google/cassandra3
    container_name: node01
    volumes:
        - ./config:/etc/cassandra/config
        - ./output/node01:/var/lib/cassandra/
    command: -Dcassandra.metricsReporterConfigFile=/etc/cassandra/config/metrics.yml
    environment:
        - CASSANDRA_SEEDS=node01,node02
        - CASSANDRA_DC=dc1
        - CASSANDRA_RACK=rack01
        - CASSANDRA_CLUSTER_NAME="Cluster"
        - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
  node02:
    image: launcher.gcr.io/google/cassandra3
    container_name: node02
    volumes:
        - ./config:/etc/cassandra/config
        - ./output/node02/:/var/lib/cassandra/
    command: -Dcassandra.metricsReporterConfigFile=/etc/cassandra/config/metrics.yml
    environment:
        - CASSANDRA_SEEDS=node01,node02
        - CASSANDRA_DC=dc2
        - CASSANDRA_RACK=rack02
        - CASSANDRA_CLUSTER_NAME="Cluster"
        - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
