version: "3"
services:
  node01:
    image: launcher.gcr.io/google/cassandra3
    container_name: node01
    volumes:
        - ./config:/etc/cassandra/config
        - ./output/node01:/usr/share/AInvariants/output/
    command: -Dcassandra.metricsReporterConfigFile=/etc/cassandra/config/metrics.yml
    environment:
        - CASSANDRA_SEEDS=node01,node02
        - CASSANDRA_DC=dc1
        - CASSANDRA_RACK=rack01
        - CASSANDRA_CLUSTER_NAME="Cluster"
        - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
  node02:
    image: launcher.gcr.io/google/cassandra3
    container_name: node02
    volumes:
        - ./config:/etc/cassandra/config
        - ./output/node02:/usr/share/AInvariants/output/
    command: -Dcassandra.metricsReporterConfigFile=/etc/cassandra/config/metrics.yml
    environment:
        - CASSANDRA_SEEDS=node01,node02
        - CASSANDRA_DC=dc2
        - CASSANDRA_RACK=rack02
        - CASSANDRA_CLUSTER_NAME="Cluster"
        - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch


        
#    ports:
#        - "7000:7000"
#        - "7001:7001"
#        - "9042:9042"
#        - "9160:9160"
#        - "7199:7199"
        
#docker network create cassandra-network
#docker container rm -f $(docker ps -a -q)
#docker run --name node01 --network cassandra-network \
# -p 7000:7000 -p 7001:7001 -p 7199:7199  -p 9042:9042  -p 9160:9160 \
# -e CASSANDRA_DC=dc1 \
# -e CASSANDRA_RACK=rack001 \
# -d launcher.gcr.io/google/cassandra3
#
#docker logs -f node01
#
#docker run --name node02 --network cassandra-network \
# -e CASSANDRA_SEEDS=node01 \
# -e CASSANDRA_DC=dc2 \
# -d launcher.gcr.io/google/cassandra3
#
#docker logs -f node02
#
#docker run --name initializer --network cassandra-network -e EXECUTOR_ENDPOINTS=node01,node02 balegas/ainvariants:latest -i