executor:
  keyspace: warehouse
  nThreads: 25
  nKeys: 10
  nOps: 1000
  deltaRange: 10
  print-interval-m-s: 1000
  percentage-r-o: 50   
  percentageDecs: 95
  sleepTimeMinMs: 50
  sleepTimeMaxMs: 100
  initValMin: 50
  initValMax: 80
  keyGeneratorClass: HotspotIntegerGenerator
  keyDistArg0: 0.7
  keyDistArg1: 0.1
  valueGeneratorClass: HotspotIntegerGenerator
  valueDistArg0: 0.7
  valueDistArg1: 0.1
  endpoints: 
    - localhost
  consistency: local-quorum
  dc-names: dc1,dc2
---
spring.profiles: printer
executor:
  outputFile: db-state.log
  print-interval-m-s: 1000 
---
spring.profiles: client
executor:
  outputFile: client-state.log
