executor:
  keyspace: warehouse
  nThreads: 25
  nKeys: 10
  nOps: 1000
  deltaRange: 10
  printIntervalMS: 1000  
  percentageDecs: 80
  sleepTimeMinMs: 50
  sleepTimeMaxMs: 100
  initValMin: 50
  initValMax: 80
  keyGeneratorClass: HotspotIntegerGenerator
  keyDistArg0: 0.7
  keyDistArg1: 0.1
  # keyDistrArg2:
  valueGeneratorClass: HotspotIntegerGenerator
  valDistArg0: 0.7
  valDistArg1: 0.1
  # valDistrArg2:
---
spring.profiles: printer
executor:
  outputFile: db-state.log
  print-interval-m-s: 1000 
---
spring.profiles: client
executor:
  outputFile: client-state.log
