executor:
  keyspace: warehouse
  nThreads: 25
  nKeys: 10
  execution-time: 120 #seconds
  client-adjust-interval: 1000 #milliseconds, 0 disable
  deltaRange: 10
  print-interval-m-s: 1000
  percentage-r-o: 50   
  percentageDecs: 95
  initValMin: 50
  initValMax: 80
  minSleepTime: 100 #milliseconds
  maxSleepTime: 150
  sleepGeneratorClass: HotspotIntegerGenerator
  sleepDistArg0: 0.7
  sleepDistArg1: 0.1
  keyGeneratorClass: HotspotIntegerGenerator
  keyDistArg0: 0.7
  keyDistArg1: 0.1
  valueGeneratorClass: HotspotIntegerGenerator
  valueDistArg0: 0.7
  valueDistArg1: 0.1
  clientsGeneratorClass: HotspotIntegerGenerator
  client-dist-arg0: 0.7
  client-dist-arg1: 0.1
  endpoints: 
    - localhost
  consistency: ONE
  dc-names: dc1
---
spring.profiles: printer
executor:
  outputFile: output/db-state.log
  print-interval-m-s: 1000 
---
spring.profiles: client
executor:
  outputFile: output/client-state.log
